# Generated by Django 2.2.3 on 2019-07-12 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
